//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLibrary.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookIssuance
    {
        public int BookIssuanceId { get; set; }
        public int BookId { get; set; }
        public int UserId { get; set; }
        public System.DateTime IssuanceDate { get; set; }
        public System.DateTime RequiredReturnDate { get; set; }
        public Nullable<System.DateTime> RealReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
